# Generated by Django 5.2.14 on 2026-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อวัตถุดิบ')),
                ('category', models.CharField(choices=[('protein', 'โปรตีน (เนื้อสัตว์ / ไข่ / อาหารทะเล)'), ('veggie', 'ผักและเครื่องเคียง'), ('spice', 'เครื่องเทศและสมุนไพร'), ('grain', 'ข้าวและแป้ง'), ('sauce', 'เครื่องปรุงและซอส'), ('other', 'อื่น ๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'วัตถุดิบ',
                'verbose_name_plural': 'วัตถุดิบทั้งหมด',
                'ordering': ['category', 'name'],
            },
        ),
    ]
