# Generated by Django 5.2.14 on 2026-05-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อเมนู')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='รูปภาพ')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='เวลาทำ (นาที)')),
                ('difficulty', models.CharField(choices=[('easy', 'ง่าย'), ('medium', 'ปานกลาง'), ('hard', 'ยาก')], default='easy', max_length=10, verbose_name='ระดับความยาก')),
                ('category', models.CharField(choices=[('thai', 'อาหารไทย'), ('street', 'อาหารตามสั่ง'), ('international', 'อาหารนานาชาติ')], default='thai', max_length=20, verbose_name='หมวดหมู่')),
                ('cooking_method', models.CharField(choices=[('fried', 'เมนูทอด'), ('boiled', 'เมนูต้ม'), ('stirfry', 'เมนูผัด'), ('salad', 'เมนูยำ / สลัด'), ('grill', 'เมนูย่าง'), ('soup', 'เมนูแกง / ซุป'), ('other', 'อื่น ๆ')], default='other', max_length=10, verbose_name='วิธีทำ')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='เผ็ด')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='แคลอรี่ (kcal)')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='ความนิยม')),
                ('is_active', models.BooleanField(default=True, verbose_name='เผยแพร่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'เมนูอาหาร',
                'verbose_name_plural': 'เมนูอาหารทั้งหมด',
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, help_text='เช่น 2 ช้อนโต๊ะ, 1 ฟอง, 200g', max_length=80, verbose_name='ปริมาณ')),
                ('is_required', models.BooleanField(default=True, help_text='หากไม่เลือก จะถือว่าเป็นวัตถุดิบเสริม (optional)', verbose_name='วัตถุดิบหลัก')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='ingredients.ingredient', verbose_name='วัตถุดิบ')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='เมนู')),
            ],
            options={
                'verbose_name': 'วัตถุดิบในเมนู',
                'verbose_name_plural': 'วัตถุดิบในเมนูทั้งหมด',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='ขั้นตอนที่')),
                ('instruction', models.TextField(verbose_name='คำอธิบายขั้นตอน')),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name='รูปภาพขั้นตอน')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='เมนู')),
            ],
            options={
                'verbose_name': 'ขั้นตอนการทำ',
                'verbose_name_plural': 'ขั้นตอนการทำทั้งหมด',
                'ordering': ['recipe', 'step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
